name: Marp Workflow

on:
  push:
    branches:
      - master
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository code.
        uses: actions/checkout@v4

      - name: Set envivonment var for chrome sandbox
        run: echo "CHROME_NO_SANDBOX=1" >> $GITHUB_ENV
      - name: Test environment var
        run: echo $CHROME_NO_SANDBOX

      - name: Set envivonment for puppeteer timeout
        run: echo "PUPPETEER_TIMEOUT=0" >> $GITHUB_ENV

      - name: Test environment var
        run: echo $PUPPETEER_TIMEOUT

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          cache: npm
          node-version-file: '.nvmrc'

      - name: Install dependencies
        run: npm ci

      - name: Build Marp slide deck
        run: CHROME_PATH=$(npx -y @puppeteer/browsers@latest install chrome@stable --path $(realpath ./tmp) | awk '{print $2}') npm run build:all

      - uses: actions/upload-artifact@v4
        with:
          name: slides
          path: |
            dist/*.pdf
            dist/*.pptx

      - name: Update username config.
        run: git config --local user.name "github-actions[bot]"
        
      - name: Update the user email config. 
        run: git config --local user.email "github-actions[bot]@users.noreply.github.com"

      - name: Stage changed files.
        run: git add dist/*

      - name: Commit changed files.
        run: git commit -m "Auto updating presentation files."

      - name: Push code to main
        run: git push origin main
